# Generated by Django 4.1.4 on 2023-09-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('uname', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=16)),
                ('mobilenum', models.CharField(max_length=11)),
            ],
        ),
    ]
