# Generated by Django 4.1.4 on 2023-09-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_remove_user_uname_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='utype',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Donor', 'Donor')], default='Donor', max_length=7),
        ),
    ]
