# Generated by Django 4.1.4 on 2023-09-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_user_utype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='utype',
            field=models.CharField(choices=[('Creator', 'Creator'), ('Donor', 'Donor')], max_length=7),
        ),
    ]
