# Generated by Django 4.1.4 on 2023-09-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_user_utype'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('details', models.TextField()),
                ('target', models.IntegerField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authen.user')),
            ],
        ),
    ]
